// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZykhg32ykqf5fNyCxBxSBNYd8CS-k3s',
    appId: '1:327065726863:web:fd25387e87652fa1fce5fa',
    messagingSenderId: '327065726863',
    projectId: 'social-media-f24c8',
    authDomain: 'social-media-f24c8.firebaseapp.com',
    storageBucket: 'social-media-f24c8.appspot.com',
    measurementId: 'G-F9ZVMEK0QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-z2lgF85Nh8nTBlhNjyObW68E2Bmb_3o',
    appId: '1:327065726863:android:2ac004edc7f35725fce5fa',
    messagingSenderId: '327065726863',
    projectId: 'social-media-f24c8',
    storageBucket: 'social-media-f24c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1QTC2lki21eCSoKZ_IvefZoy3ID7Spws',
    appId: '1:327065726863:ios:81e090faad4a6b97fce5fa',
    messagingSenderId: '327065726863',
    projectId: 'social-media-f24c8',
    storageBucket: 'social-media-f24c8.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1QTC2lki21eCSoKZ_IvefZoy3ID7Spws',
    appId: '1:327065726863:ios:f6261305fdbca86efce5fa',
    messagingSenderId: '327065726863',
    projectId: 'social-media-f24c8',
    storageBucket: 'social-media-f24c8.appspot.com',
    iosBundleId: 'com.example.socialmedia.RunnerTests',
  );
}
